services:
  - type: web
    name: srrsystem
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: NODE_VERSION
        value: 20
